// =============================================
//  FORGOTTEN WORDS - Word Database & UI Strings
//  Dynamically maps RU_WORDS (1028) and EN_WORDS (1013)
//  with Modern Synonyms, Archaisms/Historicisms, and Categories
// =============================================

const RU_ERA_MAP = {
    'a': { key: 'ancient-rus', name: 'Древняя Русь' },
    'x': { key: 'xv-xvii', name: 'XV-XVII век' },
    'v': { key: 'xviii-xix', name: 'XVIII-XIX век' }
};

const EN_ERA_MAP = {
    'm': { key: 'medieval', name: 'Medieval England' },
    'e': { key: 'elizabethan', name: 'Elizabethan Era' },
    't': { key: 'victorian', name: 'Victorian Era' }
};

// Thematic Categories
const THEMATIC_CATEGORIES = {
    "all": {
        "ru": "Все темы",
        "en": "All Topics",
        "es": "Todos los temas",
        "de": "Alle Themen",
        "it": "Tutti i temi",
        "fr": "Tous les thèmes"
    },
    "nature_body": {
        "ru": "🌿 Человек и природа",
        "en": "🌿 Anatomy & Nature",
        "es": "🌿 Hombre y naturaleza",
        "de": "🌿 Mensch & Natur",
        "it": "🌿 Uomo e natura",
        "fr": "🌿 Homme et nature"
    },
    "clothing": {
        "ru": "👗 Одежда и ткани",
        "en": "👗 Clothing & Textiles",
        "es": "👗 Ropa y telas",
        "de": "👗 Kleidung & Stoffe",
        "it": "👗 Abiti e tessuti",
        "fr": "👗 Vêtements et tissus"
    },
    "professions": {
        "ru": "🔨 Профессии и чины",
        "en": "🔨 Trades & Ranks",
        "es": "🔨 Oficios y rangos",
        "de": "🔨 Berufe & Ränge",
        "it": "🔨 Mestieri e titoli",
        "fr": "🔨 Métiers et rangs"
    },
    "measures_money": {
        "ru": "⚖️ Меры и деньги",
        "en": "⚖️ Measures & Currency",
        "es": "⚖️ Medidas y moneda",
        "de": "⚖️ Maße & Währung",
        "it": "⚖️ Misure e moneta",
        "fr": "⚖️ Mesures et monnaie"
    },
    "military": {
        "ru": "⚔️ Военное дело",
        "en": "⚔️ Warfare & Arms",
        "es": "⚔️ Arte militar y armas",
        "de": "⚔️ Kriegskunst & Waffen",
        "it": "⚔️ Arte militare e armi",
        "fr": "⚔️ Art militaire et armes"
    },
    "household": {
        "ru": "🥣 Быт и утварь",
        "en": "🥣 Household & Daily Life",
        "es": "🥣 Vida cotidiana y hogar",
        "de": "🥣 Alltag & Haushalt",
        "it": "🥣 Vita quotidiana e casa",
        "fr": "🥣 Vie quotidienne et foyer"
    },
    "speech_mind": {
        "ru": "💬 Речь и мысли",
        "en": "💬 Speech & Feelings",
        "es": "💬 Discurso y mente",
        "de": "💬 Rede & Gefühle",
        "it": "💬 Discorso e sentimenti",
        "fr": "💬 Parole et sentiments"
    }
};

// Word Types (Archaism vs Historicism)
const WORD_TYPES = {
    "all": {
        "ru": "Все слова",
        "en": "All Words",
        "es": "Todas las palabras",
        "de": "Alle Wörter",
        "it": "Tutte le parole",
        "fr": "Tous les mots"
    },
    "archaism": {
        "ru": "🏛️ Архаизмы",
        "en": "🏛️ Archaisms",
        "es": "🏛️ Arcaísmos",
        "de": "🏛️ Archaismen",
        "it": "🏛️ Arcaismi",
        "fr": "🏛️ Archaïsmes",
        "descRu": "Есть современный аналог",
        "descEn": "Has modern synonym"
    },
    "historicism": {
        "ru": "📜 Историзмы",
        "en": "📜 Historicisms",
        "es": "📜 Historicismos",
        "de": "📜 Historismen",
        "it": "📜 Storicismi",
        "fr": "📜 Historicismes",
        "descRu": "Само явление ушло в историю",
        "descEn": "Historical concept / extinct reality"
    }
};

// Curated modern synonyms for key words
const RU_CURATED_SYNONYMS = {
    'десница': 'правая рука',
    'шуйца': 'левая рука',
    'чело': 'лоб',
    'ланиты': 'щёки',
    'ланита': 'щека',
    'перст': 'палец',
    'вежды': 'веки',
    'уста': 'губы, рот',
    'зеницы': 'глаза, зрачки',
    'выя': 'шея',
    'рамена': 'плечи',
    'длань': 'ладонь',
    'чресла': 'бёдра, поясница',
    'перси': 'грудь',
    'лик': 'лицо, образ',
    'очи': 'глаза',
    'пясть': 'кулак',
    'чрево': 'живот, утроба',
    'ярёмо': 'хомут, иго',
    'рёбры': 'рёбра',
    'стегно': 'бедро',
    'тать': 'вор, грабитель',
    'татба': 'кража, воровство',
    'супостат': 'враг, недруг',
    'брань': 'битва, война',
    'ратник': 'воин, ополченец',
    'витязь': 'богатырь, рыцарь',
    'град': 'город',
    'брег': 'берег',
    'злато': 'золото',
    'сребро': 'серебро',
    'дщерь': 'дочь',
    'чадо': 'дитя, ребёнок',
    'отрок': 'подросток, юноша',
    'ветрило': 'парус',
    'лодья': 'лодка, ладья',
    'одр': 'кровать, постель',
    'покои': 'комнаты',
    'чертог': 'дворец, палаты',
    'корчма': 'трактир, таверна',
    'купец': 'торговец',
    'сонмище': 'толпа, сборище',
    'днесь': 'сегодня',
    'вельми': 'очень, весьма',
    'зело': 'очень',
    'паче': 'больше, сильнее',
    'токмо': 'только',
    'яко': 'как, будто',
    'абы': 'лишь бы',
    'коли': 'если',
    'ежели': 'если',
    'понеже': 'потому что',
    'почто': 'зачем, почему',
    'доколе': 'до каких пор',
    'давеча': 'недавно',
    'намедни': 'на днях',
    'сызнова': 'заново',
    'вкупе': 'вместе',
    'воочию': 'своими глазами',
    'всуе': 'напрасно, зря',
    'присно': 'всегда, вечно',
    'уповать': 'надеяться',
    'внимать': 'слушать',
    'глаголать': 'говорить',
    'вещать': 'говорить, пророчествовать',
    'зреть': 'видеть, смотреть',
    'взирать': 'смотреть',
    'алкать': 'жаждать, голодать',
    'ведать': 'знать',
    'чуять': 'чувствовать',
    'мнить': 'думать, полагать',
    'чаять': 'ожидать, надеяться',
    'сетовать': 'жаловаться',
    'роптать': 'выражать недовольство',
    'почивать': 'спать',
    'воспрять': 'ожить, очнуться',
    'ликовать': 'радоваться',
    'кручиниться': 'грустить, печалиться',
    'яриться': 'злиться, гневаться',
    'шествовать': 'торжественно идти',
    'созидать': 'строить, создавать',
    'зиждать': 'строить, основывать',
    'стяжать': 'накопить, приобрести',
    'мзда': 'плата, вознаграждение',
    'даяние': 'дар, милостыня'
};

const EN_CURATED_SYNONYMS = {
    'forsooth': 'in truth, indeed',
    'prithee': 'please, I pray you',
    'methinks': 'it seems to me, I think',
    'quoth': 'said, spoke',
    'perchance': 'perhaps, maybe',
    'forsake': 'abandon, leave',
    'anon': 'soon, shortly',
    'nay': 'no',
    'fie': 'shame!, nonsense!',
    'alack': 'alas!, woe!',
    'hark': 'listen!, hear!',
    'marry': 'indeed!, by Mary!',
    'grammercy': 'thank you!',
    'sooth': 'truth, reality',
    'gainsay': 'deny, contradict',
    'ween': 'think, believe',
    'hither': 'here, to this place',
    'thither': 'there, to that place',
    'whither': 'where, to what place',
    'hence': 'from here, away',
    'thence': 'from there',
    'whence': 'from where',
    'welkin': 'sky, heavens',
    'weasand': 'windpipe, throat',
    'wight': 'person, living being',
    'whilom': 'formerly, once',
    'eftsoons': 'soon after, shortly',
    'certes': 'certainly, surely',
    'varlet': 'rascal, servant',
    'scullion': 'kitchen servant',
    'bootless': 'useless, in vain',
    'fain': 'gladly, willingly',
    'maugre': 'in spite of, despite',
    'wont': 'accustomed, habit',
    'nought': 'nothing, zero',
    'aught': 'anything',
    'soothsayer': 'fortune teller, prophet',
    'eldritch': 'eerie, ghostly',
    'wraith': 'ghost, phantom',
    'poltroon': 'coward',
    'craven': 'cowardly',
    'dastard': 'sneaking coward',
    'popinjay': 'vain strutting person',
    'nincompoop': 'fool, idiot',
    'halcyon': 'peaceful, idyllic',
    'hubris': 'excessive pride, arrogance',
    'guerdon': 'reward, prize'
};

// Helper: categorize word and extract synonym
function analyzeWord(word, pronunciation, eraKey, meaning, lang) {
    const wLow = word.toLowerCase().trim();
    const mLow = meaning.toLowerCase();

    // 1. Synonym extraction
    let synonym = '';
    if (lang === 'ru' && RU_CURATED_SYNONYMS[wLow]) {
        synonym = RU_CURATED_SYNONYMS[wLow];
    } else if (lang === 'en' && EN_CURATED_SYNONYMS[wLow]) {
        synonym = EN_CURATED_SYNONYMS[wLow];
    } else {
        // Extract natural first segment or full meaning
        let firstClause = meaning.split(/[;(\-—]/)[0].trim();
        if (firstClause.endsWith('.')) {
            firstClause = firstClause.slice(0, -1).trim();
        }
        if (lang === 'en') {
            synonym = firstClause.replace(/^(a|an|the|to)\s+/i, '');
        } else {
            synonym = firstClause.replace(/^(один из|одна из|вид|род)\s+/i, '');
        }
        // NEVER truncate or cut off: full designation is preserved
        if (synonym.length > 0) {
            synonym = synonym.charAt(0).toLowerCase() + synonym.slice(1);
        }
    }

    // 2. Classify word type: Archaism vs Historicism
    // Historicisms: specific extinct items, ranks, ancient money, medieval arms/vessels
    let wordType = 'archaism';
    const historicismKeywords = [
        'чин', 'должност', 'монет', 'денежн', 'мера длин', 'мера вес', 'ведомств',
        'сословие', 'подать', 'оброк', 'барщин', 'приказ', 'челобит', 'кафтан',
        'кольчуг', 'шелом', 'пищаль', 'секир', 'ендов', 'братин', 'судно', 'ладья',
        'судн', 'дворян', 'бояр', 'окольнич', 'стольник', 'кравч', 'тиун',
        'officer', 'magistrate', 'currency', 'coin', 'feudal', 'vassal', 'serf',
        'armor', 'armour', 'weapon', 'sword', 'ship', 'vessel', 'caravel', 'galleon',
        'carriage', 'measure', 'guilder', 'florin', 'doubloon', 'shilling', 'groat'
    ];
    if (historicismKeywords.some(kw => mLow.includes(kw) || wLow.includes(kw))) {
        wordType = 'historicism';
    }

    // 3. Classify category
    let category = 'speech_mind';
    if (mLow.includes('одежд') || mLow.includes('ткань') || mLow.includes('плат') || mLow.includes('рубах') || mLow.includes('кафтан') || mLow.includes('шапк') || mLow.includes('сапог') || mLow.includes('шелк') || mLow.includes('бархат') || mLow.includes('cloth') || mLow.includes('fabric') || mLow.includes('garment') || mLow.includes('silk') || mLow.includes('tunic') || mLow.includes('dress') || mLow.includes('hat') || mLow.includes('bonnet')) {
        category = 'clothing';
    } else if (mLow.includes('чин') || mLow.includes('должност') || mLow.includes('ремесл') || mLow.includes('мастер') || mLow.includes('слуг') || mLow.includes('бояр') || mLow.includes('купец') || mLow.includes('officer') || mLow.includes('servant') || mLow.includes('craftsman') || mLow.includes('profession') || mLow.includes('trade') || mLow.includes('reeve') || mLow.includes('bailiff') || mLow.includes('worker')) {
        category = 'professions';
    } else if (mLow.includes('монет') || mLow.includes('денег') || mLow.includes('рубл') || mLow.includes('копейк') || mLow.includes('алтын') || mLow.includes('пуд') || mLow.includes('верст') || mLow.includes('аршин') || mLow.includes('сажен') || mLow.includes('золотник') || mLow.includes('coin') || mLow.includes('currency') || mLow.includes('measure') || mLow.includes('weight') || mLow.includes('pound') || mLow.includes('shilling') || mLow.includes('fathom')) {
        category = 'measures_money';
    } else if (mLow.includes('оруж') || mLow.includes('меч') || mLow.includes('щит') || mLow.includes('доспех') || mLow.includes('шлем') || mLow.includes('рать') || mLow.includes('войск') || mLow.includes('битва') || mLow.includes('секир') || mLow.includes('лучник') || mLow.includes('крепост') || mLow.includes('башня') || mLow.includes('weapon') || mLow.includes('armor') || mLow.includes('sword') || mLow.includes('shield') || mLow.includes('war') || mLow.includes('castle') || mLow.includes('fortress') || mLow.includes('knight')) {
        category = 'military';
    } else if (mLow.includes('посуд') || mLow.includes('сосуд') || mLow.includes('изб') || mLow.includes('печь') || mLow.includes('утварь') || mLow.includes('кубок') || mLow.includes('сундук') || mLow.includes('ларец') || mLow.includes('ковш') || mLow.includes('чаш') || mLow.includes('дом') || mLow.includes('пир') || mLow.includes('кухн') || mLow.includes('vessel') || mLow.includes('pot') || mLow.includes('chest') || mLow.includes('hearth') || mLow.includes('cup') || mLow.includes('house') || mLow.includes('table') || mLow.includes('inn') || mLow.includes('ale')) {
        category = 'household';
    } else if (mLow.includes('рук') || mLow.includes('ног') || mLow.includes('глаз') || mLow.includes('лиц') || mLow.includes('щек') || mLow.includes('шея') || mLow.includes('лоб') || mLow.includes('палец') || mLow.includes('грудь') || mLow.includes('живот') || mLow.includes('лес') || mLow.includes('рек') || mLow.includes('трава') || mLow.includes('гор') || mLow.includes('птиц') || mLow.includes('звер') || mLow.includes('body') || mLow.includes('hand') || mLow.includes('eye') || mLow.includes('face') || mLow.includes('head') || mLow.includes('neck') || mLow.includes('throat') || mLow.includes('river') || mLow.includes('hill') || mLow.includes('tree') || mLow.includes('wind') || mLow.includes('flower')) {
        category = 'nature_body';
    }

    return { synonym, wordType, category };
}

const WORDS_DATABASE = [];

// Ingest Russian words
if (typeof RU_WORDS !== 'undefined' && Array.isArray(RU_WORDS)) {
    RU_WORDS.forEach((item, index) => {
        const eraInfo = RU_ERA_MAP[item[2]] || RU_ERA_MAP['v'];
        const analysis = analyzeWord(item[0], item[1], item[2], item[3], 'ru');
        WORDS_DATABASE.push({
            id: 'ru_' + (index + 1),
            word: item[0],
            lang: 'ru',
            pronunciation: item[1] || `[${item[0].toLowerCase()}]`,
            era: eraInfo.name,
            eraKey: eraInfo.key,
            meaning: item[3],
            synonym: analysis.synonym,
            wordType: analysis.wordType,
            category: analysis.category,
            etymology: item[4] || 'Старинное русское слово.',
            usage: 'Употреблялось в литературных памятниках и живой речи соответствующей эпохи.',
            quote: item[5] || `«${item[0]} встречается в старинных летописях и сказаниях.»`,
            source: item[6] || 'Словарь В.И. Даля',
            tags: [item[0].toLowerCase(), eraInfo.key, analysis.wordType, analysis.category, analysis.synonym]
        });
    });
}

// Ingest English words
if (typeof EN_WORDS !== 'undefined' && Array.isArray(EN_WORDS)) {
    EN_WORDS.forEach((item, index) => {
        const eraInfo = EN_ERA_MAP[item[2]] || EN_ERA_MAP['t'];
        const analysis = analyzeWord(item[0], item[1], item[2], item[3], 'en');
        WORDS_DATABASE.push({
            id: 'en_' + (index + 1),
            word: item[0],
            lang: 'en',
            pronunciation: item[1] || `/${item[0].toLowerCase()}/`,
            era: eraInfo.name,
            eraKey: eraInfo.key,
            meaning: item[3],
            synonym: analysis.synonym,
            wordType: analysis.wordType,
            category: analysis.category,
            etymology: item[4] || 'From archaic English usage.',
            usage: 'Commonly found in classic English literature, plays, and historical records.',
            quote: item[5] || `"${item[0]} was celebrated in ancient English verse."`,
            source: item[6] || 'Oxford English Dictionary / Historical Corpus',
            tags: [item[0].toLowerCase(), eraInfo.key, analysis.wordType, analysis.category, analysis.synonym]
        });
    });
}

// Ingest Extra Languages (fr, de, la, es, it, cu)
if (typeof EXTRA_WORDS !== 'undefined' && Array.isArray(EXTRA_WORDS)) {
    EXTRA_WORDS.forEach((item, index) => {
        if (item && item.word && item.lang) {
            WORDS_DATABASE.push({
                id: (item.lang || 'ext') + '_' + (index + 1),
                word: item.word,
                lang: item.lang,
                pronunciation: item.pronunciation || `[${item.word}]`,
                era: item.era || 'Историческая эпоха',
                eraKey: item.eraKey || 'renaissance',
                meaning: item.meaning,
                meanings: item.meanings || { ru: item.meaning },
                synonym: item.synonym || '',
                synonyms: item.synonyms || { ru: item.synonym },
                wordType: item.wordType || 'archaism',
                category: item.category || 'speech_mind',
                etymology: item.etymology || 'Старинное слово.',
                etymologies: item.etymologies || { ru: item.etymology },
                usage: item.usage || 'Встречается в классических памятниках литературы.',
                quote: item.quote || `«${item.word}»`,
                source: item.source || 'Классический словарь',
                tags: [item.word.toLowerCase(), item.eraKey || '', item.wordType || '', item.category || '', (item.synonym || '').toLowerCase()]
            });
        }
    });
}

// Load user-contributed words from localStorage if in browser
if (typeof window !== 'undefined' && window.localStorage) {
    try {
        const userWords = JSON.parse(localStorage.getItem('fw_user_suggested_words') || '[]');
        userWords.forEach(uw => {
            WORDS_DATABASE.unshift(uw); // Put community words right at top of their lang
        });
    } catch (e) {
        console.warn('Failed to parse user words from localStorage:', e);
    }
}

// Era labels for filters (bilingual)
const ERA_LABELS = {
    "ancient-rus": {
        "ru": "Древняя Русь",
        "en": "Ancient Rus",
        "es": "Antigua Rus",
        "de": "Altes Rus",
        "it": "Antica Rus",
        "fr": "Ancienne Rus'"
    },
    "xv-xvii": {
        "ru": "XV-XVII век",
        "en": "15th-17th Century",
        "es": "Siglos XV-XVII",
        "de": "15.-17. Jahrhundert",
        "it": "Secoli XV-XVII",
        "fr": "XVe-XVIIe siècle"
    },
    "xviii-xix": {
        "ru": "XVIII-XIX век",
        "en": "18th-19th Century",
        "es": "Siglos XVIII-XIX",
        "de": "18.-19. Jahrhundert",
        "it": "Secoli XVIII-XIX",
        "fr": "XVIIIe-XIXe siècle"
    },
    "medieval": {
        "ru": "Средневековье",
        "en": "Medieval England",
        "es": "Edad Media",
        "de": "Mittelalter",
        "it": "Medioevo",
        "fr": "Moyen Âge"
    },
    "elizabethan": {
        "ru": "Елизаветинская эпоха",
        "en": "Elizabethan Era",
        "es": "Época isabelina",
        "de": "Elisabethanisches Zeitalter",
        "it": "Epoca elisabettiana",
        "fr": "Époque élisabéthaine"
    },
    "victorian": {
        "ru": "Викторианская эпоха",
        "en": "Victorian Era",
        "es": "Época victoriana",
        "de": "Viktorianisches Zeitalter",
        "it": "Epoca vittoriana",
        "fr": "Époque victorienne"
    },
    "classical-antiquity": {
        "ru": "Античность (Древний Рим)",
        "en": "Classical Antiquity",
        "es": "Antigüedad clásica",
        "de": "Klassische Antike",
        "it": "Antichità classica",
        "fr": "Antiquité classique"
    },
    "renaissance": {
        "ru": "Эпоха Возрождения",
        "en": "Renaissance",
        "es": "Renacimiento",
        "de": "Renaissance",
        "it": "Rinascimento",
        "fr": "Renaissance"
    },
    "golden-age": {
        "ru": "Золотой век",
        "en": "Golden Age (Siglo de Oro)",
        "es": "Siglo de Oro",
        "de": "Goldenes Zeitalter",
        "it": "Secolo d'Oro",
        "fr": "Siècle d'Or"
    },
    "enlightenment": {
        "ru": "Эпоха Просвещения",
        "en": "Age of Enlightenment",
        "es": "Ilustración",
        "de": "Aufklärung",
        "it": "Illuminismo",
        "fr": "Siècle des Lumières"
    },
    "middle-ages": {
        "ru": "Средние века",
        "en": "Middle Ages",
        "es": "Medievo",
        "de": "Mittelalter",
        "it": "Medioevo",
        "fr": "Moyen Âge"
    },
    "church-slavonic": {
        "ru": "Церковнославянский",
        "en": "Old Church Slavonic",
        "es": "Eslavo eclesiástico",
        "de": "Altkirchenslawisch",
        "it": "Antico slavo ecclesiastico",
        "fr": "Vieux-slave"
    }
};

// UI translation strings
const UI_STRINGS = {
    "ru": {
        "logoTitle": "Забытые Слова",
        "logoSubtitle": "Словарь редких слов",
        "wordOfDay": "Слово дня",
        "randomWord": "Случайное слово",
        "copy": "Копировать",
        "copied": "Скопировано!",
        "wordsInDict": "слов в словаре",
        "eras": "эпох",
        "languages": "языка",
        "dictionary": "Словарь",
        "dictDesc": "Исследуйте слова, которые когда-то звучали в каждом доме",
        "language": "Язык:",
        "era": "Эпоха:",
        "category": "Тематика:",
        "wordType": "Тип слова:",
        "all": "Все",
        "allWords": "Все слова",
        "allCategories": "Все темы",
        "allEras": "Все эпохи",
        "typeArchaism": "🏛️ Архаизмы (есть синоним)",
        "typeHistoricism": "📜 Историзмы (ушедшая реалия)",
        "searchPlaceholder": "Поиск слова или современного синонима...",
        "notFound": "Слов не найдено. Попробуйте другой запрос или сбросьте фильтры.",
        "showMore": "Показать ещё",
        "aboutTitle": "О проекте",
        "aboutP1": "<strong>Забытые Слова</strong> - это интерактивный словарь устаревших и вышедших из употребления слов русского и английского языков.",
        "aboutP2": "Мы собираем архаизмы, историзмы и редкие слова из классической литературы - от Пушкина и Достоевского до Шекспира и Диккенса - и объясняем их живым, понятным языком, подбирая современные синонимы.",
        "aboutP3": "Каждый день мы показываем новое забытое слово, чтобы вы могли расширить свой словарный запас и взглянуть на мир глазами прошлых поколений.",
        "feat1Title": "Современные аналоги",
        "feat1Desc": "К каждому слову подобран понятный синоним из сегодняшнего языка",
        "feat2Title": "Два богатых языка",
        "feat2Desc": "Более 2 000 русских и английских старинных слов без смешивания",
        "feat3Title": "Архаизмы и историзмы",
        "feat3Desc": "Чёткое разделение слов на заменённые и исчезнувшие явления",
        "feat4Title": "Викторины и игры",
        "feat4Desc": "Проверьте себя в игре «Угадай значение» или подберите синоним",
        "footerCopy": "© 2026 Забытые Слова. Сохраняем язык прошлого для будущего.",
        "footerMade": "Сделано с ❤️ для любителей словесности",
        "etymology": "Происхождение",
        "usageLabel": "Употребление",
        "synonymLabel": "Современный аналог:",
        "navWordOfDay": "Слово дня",
        "navDictionary": "Словарь",
        "navQuiz": "Викторина",
        "navSuggest": "Предложить слово",
        "navAbout": "О проекте",
        "tabRu": "Русские слова",
        "tabEn": "English words",
        "quizTitle": "Викторина забытых слов",
        "quizSubtitle": "Проверьте свою эрудицию и словарный запас!",
        "score": "Счёт",
        "streak": "Серия",
        "nextQuestion": "Следующее слово",
        "quizModeMeaning": "📖 Угадай значение",
        "quizModeSynonym": "✨ Современный аналог",
        "quizPromptMeaning": "Выберите правильное значение слова:",
        "quizPromptSynonym": "Подберите верный современный синоним:",
        "quizFeedbackCorrect": "Верно! Великолепная эрудиция!",
        "quizFeedbackWrong": "Не совсем так. Правильный ответ:",
        "suggestTitle": "Предложить забытое слово",
        "suggestSubtitle": "Услышали редкое слово от бабушки или встретили в старой книге? Предложите его для добавления в словарь - мы рассмотрим вашу заявку!",
        "suggestWordLabel": "Слово *",
        "suggestWordPlaceholder": "Например: Посолонь",
        "suggestLangLabel": "Язык",
        "suggestSynonymLabel": "Современный аналог / синоним *",
        "suggestSynonymPlaceholder": "Например: По ходу солнца / по часовой стрелке",
        "suggestTypeLabel": "Тип слова",
        "suggestCategoryLabel": "Тематическая категория",
        "suggestMeaningLabel": "Подробное толкование и значение *",
        "suggestMeaningPlaceholder": "Что означало это слово, как использовалось в старину...",
        "suggestSourceLabel": "Откуда вы узнали это слово? (книга, бабушка, диалект)",
        "suggestSourcePlaceholder": "Например: Услышал от дедушки в Архангельской области",
        "suggestAuthorLabel": "Ваше имя или псевдоним (для благодарности в карточке)",
        "suggestAuthorPlaceholder": "Например: Иван Читатель",
        "submitWord": "Отправить на рассмотрение",
        "themeTitle": "Тема оформления",
        "toastCopiedWord": "Слово скопировано в буфер!",
        "toastWordAdded": "Заявка со словом успешно отправлена автору на модерацию!",
        "heroSearchTitle": "Поиск по словарю забытых слов",
        "heroSearchSubtitle": "Более 2 000 редких слов с современными аналогами и толкованиями",
        "heroSearchPlaceholder": "Поиск слова или современного синонима (например: Шуйца, Посолонь)...",
        "liveSearchSeeAll": "Показать все результаты в словаре",
        "liveSearchNone": "Забытых слов по такому запросу не найдено",
        "actionLangLabel": "Язык:",
        "actionFontLabel": "Шрифт:",
        "actionThemeLabel": "Тема:",
        "themePapyrus": "Папирус",
        "themeDark": "Тёмная",
        "navDonate": "Поддержать",
        "footerDonate": "☕ Поддержать автора",
        "donateTitle": "Поддержка автора и проекта",
        "donateDesc": "Forgotten Words — независимый некоммерческий проект по спасению и сохранению редких старинных слов. Ваше пожертвование помогает оплачивать сервера, расширять базу и развивать словарь!",
        "boostySub": "Подписка или разовый донат с любой карты",
        "cloudtipsSub": "Быстрый перевод через СБП и карты РФ",
        "donattySub": "Удобные донаты в пару кликов",
        "donateNote": "Спасибо каждому, кто ценит историю и красоту языка! ❤️",
        "statLangsLabel": "языков"
    },
    "en": {
        "logoTitle": "Forgotten Words",
        "logoSubtitle": "Dictionary of Lost Words",
        "wordOfDay": "Word of the Day",
        "randomWord": "Random Word",
        "copy": "Copy",
        "copied": "Copied!",
        "wordsInDict": "words in dictionary",
        "eras": "historical eras",
        "languages": "languages",
        "dictionary": "Dictionary",
        "dictDesc": "Explore words that once echoed in every household",
        "language": "Language:",
        "era": "Era:",
        "category": "Category:",
        "wordType": "Word Type:",
        "all": "All",
        "allWords": "All words",
        "allCategories": "All categories",
        "allEras": "All eras",
        "typeArchaism": "🏛️ Archaisms (has modern synonym)",
        "typeHistoricism": "📜 Historicisms (historical relic)",
        "searchPlaceholder": "Search for a word or modern synonym...",
        "notFound": "No words found. Try a different query or reset filters.",
        "showMore": "Show More",
        "aboutTitle": "About the Project",
        "aboutP1": "<strong>Forgotten Words</strong> is an interactive dictionary of archaic and obsolete words from the Russian and English languages.",
        "aboutP2": "We collect archaisms, historicisms, and rare words from classical literature - from Pushkin and Dostoevsky to Shakespeare and Dickens - and pair each with clear modern equivalents.",
        "aboutP3": "Every day we feature a new forgotten word, so you can expand your vocabulary and see the world through the eyes of past generations.",
        "feat1Title": "Modern Counterparts",
        "feat1Desc": "Every archaic word includes a direct contemporary synonym",
        "feat2Title": "Two Rich Languages",
        "feat2Desc": "Over 2,000 Russian and English words with strict separation",
        "feat3Title": "Archaisms & Historicisms",
        "feat3Desc": "Clear distinction between replaced words and extinct realities",
        "feat4Title": "Interactive Quizzes",
        "feat4Desc": "Test your knowledge in \"Guess the Meaning\" or synonym match",
        "footerCopy": "© 2026 Forgotten Words. Preserving the language of the past for the future.",
        "footerMade": "Made with ❤️ for word lovers",
        "etymology": "Etymology",
        "usageLabel": "Usage",
        "synonymLabel": "Modern equivalent:",
        "navWordOfDay": "Word of the Day",
        "navDictionary": "Dictionary",
        "navQuiz": "Quiz",
        "navSuggest": "Suggest Word",
        "navAbout": "About",
        "tabRu": "Russian words",
        "tabEn": "English words",
        "quizTitle": "Literary Words Quiz",
        "quizSubtitle": "Test your historical vocabulary and intuition!",
        "score": "Score",
        "streak": "Streak",
        "nextQuestion": "Next Word",
        "quizModeMeaning": "📖 Guess Meaning",
        "quizModeSynonym": "✨ Modern Synonym",
        "quizPromptMeaning": "Choose the correct meaning of this word:",
        "quizPromptSynonym": "Select the correct modern equivalent:",
        "quizFeedbackCorrect": "Correct! Outstanding erudition!",
        "quizFeedbackWrong": "Not quite. The correct answer was:",
        "suggestTitle": "Suggest a Forgotten Word",
        "suggestSubtitle": "Heard a rare word or encountered one in an old book? Submit your proposal - our editors will review it!",
        "suggestWordLabel": "Word *",
        "suggestWordPlaceholder": "E.g., Overmorrow",
        "suggestLangLabel": "Language",
        "suggestSynonymLabel": "Modern equivalent / synonym *",
        "suggestSynonymPlaceholder": "E.g., The day after tomorrow",
        "suggestTypeLabel": "Word type",
        "suggestCategoryLabel": "Category",
        "suggestMeaningLabel": "Detailed meaning & definition *",
        "suggestMeaningPlaceholder": "What this word meant and how it was used in old times...",
        "suggestSourceLabel": "Where did you discover this word? (book, folklore, elder)",
        "suggestSourcePlaceholder": "E.g., Shakespeare, Hamlet, or local countryside phrase",
        "suggestAuthorLabel": "Your name or moniker (for credit in card)",
        "suggestAuthorPlaceholder": "E.g., Arthur the Bibliophile",
        "submitWord": "Submit for Review",
        "themeTitle": "Theme",
        "toastCopiedWord": "Word copied to clipboard!",
        "toastWordAdded": "Word suggestion submitted for review! Thank you!",
        "heroSearchTitle": "Search the Dictionary of Lost Words",
        "heroSearchSubtitle": "Over 2,000 rare and archaic words with direct modern equivalents",
        "heroSearchPlaceholder": "Search by archaic word or modern synonym (e.g. Anon, Perchance)...",
        "liveSearchSeeAll": "View all matching words in dictionary",
        "liveSearchNone": "No forgotten words found matching this query",
        "actionLangLabel": "Language:",
        "actionFontLabel": "Font:",
        "actionThemeLabel": "Theme:",
        "themePapyrus": "Papyrus",
        "themeDark": "Dark",
        "navDonate": "Support",
        "footerDonate": "☕ Support the Author",
        "donateTitle": "Support the Author & Project",
        "donateDesc": "Forgotten Words is an independent non-profit project dedicated to preserving rare and archaic words. Your donation helps pay for servers, expand the lexicon, and develop new features!",
        "boostySub": "Subscription or one-time donation via card",
        "cloudtipsSub": "Quick transfer via card & payment apps",
        "donattySub": "Convenient tip in a few clicks",
        "donateNote": "Thank you to everyone who cherishes the history and beauty of language! ❤️",
        "statLangsLabel": "languages"
    },
    "es": {
        "logoTitle": "Forgotten Words",
        "logoSubtitle": "Diccionario de Palabras Perdidas",
        "wordOfDay": "Palabra del Día",
        "randomWord": "Palabra Aleatoria",
        "copy": "Copiar",
        "copied": "¡Copiado!",
        "wordsInDict": "palabras en el diccionario",
        "eras": "épocas históricas",
        "languages": "idiomas",
        "dictionary": "Diccionario",
        "dictDesc": "Explora vocablos que antaño resonaban en cada hogar",
        "language": "Idioma:",
        "era": "Época:",
        "category": "Categoría:",
        "wordType": "Tipo de palabra:",
        "all": "Todas",
        "allWords": "Todas las palabras",
        "allCategories": "Todas las categorías",
        "allEras": "Todas las épocas",
        "typeArchaism": "🏛️ Arcaísmos (poseen sinónimo moderno)",
        "typeHistoricism": "📜 Historicismos (reliquia histórica)",
        "searchPlaceholder": "Busca una palabra o sinónimo moderno...",
        "notFound": "No se encontraron palabras. Prueba con otra consulta o restablece los filtros.",
        "showMore": "Mostrar Más",
        "aboutTitle": "Acerca del Proyecto",
        "aboutP1": "<strong>Forgotten Words</strong> es un diccionario interactivo de vocablos arcaicos y en desuso de los idiomas ruso e inglés.",
        "aboutP2": "Recopilamos arcaísmos, historicismos y términos raros de la literatura clásica —desde Pushkin y Dostoievski hasta Shakespeare y Dickens— vinculando cada uno con su equivalente moderno.",
        "aboutP3": "Cada día presentamos una nueva palabra olvidada para que puedas enriquecer tu vocabulario y contemplar el mundo a través de los ojos de generaciones pasadas.",
        "feat1Title": "Equivalentes Modernos",
        "feat1Desc": "Cada palabra arcaica incluye un sinónimo contemporáneo directo",
        "feat2Title": "Dos Ricos Idiomas",
        "feat2Desc": "Más de 2000 palabras en ruso e inglés con rigurosa separación",
        "feat3Title": "Arcaísmos e Historicismos",
        "feat3Desc": "Distinción clara entre términos reemplazados y realidades extintas",
        "feat4Title": "Cuestionarios Interactivos",
        "feat4Desc": "Pon a prueba tu erudición en \"Adivina el significado\" o emparejamiento de sinónimos",
        "footerCopy": "© 2026 Forgotten Words. Preservando el lenguaje del pasado para el porvenir.",
        "footerMade": "Hecho con ❤️ para los amantes de las palabras",
        "etymology": "Etimología",
        "usageLabel": "Uso",
        "synonymLabel": "Equivalente moderno:",
        "navWordOfDay": "Palabra del Día",
        "navDictionary": "Diccionario",
        "navQuiz": "Cuestionario",
        "navSuggest": "Sugerir Palabra",
        "navAbout": "Acerca de",
        "tabRu": "Palabras en ruso",
        "tabEn": "Palabras en inglés",
        "quizTitle": "Cuestionario de Vocabulario Literario",
        "quizSubtitle": "¡Pon a prueba tu intuición y erudición histórica!",
        "score": "Puntuación",
        "streak": "Racha",
        "nextQuestion": "Siguiente Palabra",
        "quizModeMeaning": "📖 Adivinar Significado",
        "quizModeSynonym": "✨ Sinónimo Moderno",
        "quizPromptMeaning": "Elige el significado correcto de esta palabra:",
        "quizPromptSynonym": "Selecciona el equivalente moderno correcto:",
        "quizFeedbackCorrect": "¡Correcto! ¡Excepcional erudición!",
        "quizFeedbackWrong": "No exactamente. La respuesta correcta era:",
        "suggestTitle": "Sugerir una Palabra Olvidada",
        "suggestSubtitle": "¿Escuchaste un término poco común o lo hallaste en un libro antiguo? Envía tu propuesta; ¡nuestros editores la evaluarán!",
        "suggestWordLabel": "Palabra *",
        "suggestWordPlaceholder": "Ej., Pasado mañana",
        "suggestLangLabel": "Idioma",
        "suggestSynonymLabel": "Equivalente / sinónimo moderno *",
        "suggestSynonymPlaceholder": "Ej., El día posterior a mañana",
        "suggestTypeLabel": "Tipo de palabra",
        "suggestCategoryLabel": "Categoría",
        "suggestMeaningLabel": "Significado detallado y definición *",
        "suggestMeaningPlaceholder": "Lo que este vocablo significaba y cómo se empleaba antaño...",
        "suggestSourceLabel": "¿Dónde descubriste esta palabra? (libro, folclore, ancianos)",
        "suggestSourcePlaceholder": "Ej., Shakespeare, Hamlet o frase popular local",
        "suggestAuthorLabel": "Tu nombre o seudónimo (para crédito en la tarjeta)",
        "suggestAuthorPlaceholder": "Ej., Arturo el Bibliófilo",
        "submitWord": "Enviar para Revisión",
        "themeTitle": "Tema",
        "toastCopiedWord": "¡Palabra copiada al portapapeles!",
        "toastWordAdded": "¡Sugerencia de palabra enviada para revisión! ¡Muchas gracias!",
        "heroSearchTitle": "Busca en el Diccionario de Palabras Perdidas",
        "heroSearchSubtitle": "Más de 2000 vocablos raros y arcaicos con equivalentes modernos directos",
        "heroSearchPlaceholder": "Busca por término arcaico o sinónimo moderno (ej. antaño, guise)...",
        "liveSearchSeeAll": "Ver todas las palabras coincidentes en el diccionario",
        "liveSearchNone": "No se encontraron palabras olvidadas que coincidan con esta búsqueda",
        "actionLangLabel": "Idioma:",
        "actionFontLabel": "Tipografía:",
        "actionThemeLabel": "Tema:",
        "themePapyrus": "Papiro",
        "themeDark": "Oscuro",
        "navDonate": "Apoyar",
        "footerDonate": "☕ Apoyar al Autor",
        "donateTitle": "Apoyar al Autor y al Proyecto",
        "donateDesc": "Forgotten Words es un proyecto independiente y sin ánimo de lucro dedicado a preservar vocablos raros y arcaicos. ¡Tu donación ayuda a sufragar servidores, ampliar el léxico y desarrollar nuevas funciones!",
        "boostySub": "Suscripción o donación única mediante tarjeta",
        "cloudtipsSub": "Transferencia rápida por tarjeta y aplicaciones de pago",
        "donattySub": "Propina cómoda en pocos clics",
        "donateNote": "¡Gracias a todos los que atesoran la historia y la belleza del lenguaje! ❤️",
        "statLangsLabel": "idiomas"
    },
    "de": {
        "logoTitle": "Forgotten Words",
        "logoSubtitle": "Wörterbuch der verlorenen Worte",
        "wordOfDay": "Wort des Tages",
        "randomWord": "Zufälliges Wort",
        "copy": "Kopieren",
        "copied": "Kopiert!",
        "wordsInDict": "Worte im Wörterbuch",
        "eras": "historische Epochen",
        "languages": "Sprachen",
        "dictionary": "Wörterbuch",
        "dictDesc": "Ergründen Sie Worte, die einst in jedem Hause erklangen",
        "language": "Sprache:",
        "era": "Epoche:",
        "category": "Kategorie:",
        "wordType": "Wortart:",
        "all": "Alle",
        "allWords": "Alle Worte",
        "allCategories": "Alle Kategorien",
        "allEras": "Alle Epochen",
        "typeArchaism": "🏛️ Archaismen (mit moderner Entsprechung)",
        "typeHistoricism": "📜 Historismen (historisches Relikt)",
        "searchPlaceholder": "Nach einem Wort oder modernen Synonym suchen...",
        "notFound": "Keine Worte gefunden. Versuchen Sie eine andere Suche oder setzen Sie die Filter zurück.",
        "showMore": "Mehr anzeigen",
        "aboutTitle": "Über das Projekt",
        "aboutP1": "<strong>Forgotten Words</strong> ist ein interaktives Wörterbuch archaischer und veralteter Worte der russischen und englischen Sprache.",
        "aboutP2": "Wir sammeln Archaismen, Historismen und seltene Worte aus der klassischen Literatur – von Puschkin und Dostojewski bis hin zu Shakespeare und Dickens – und stellen jedem einen klaren modernen Begriff zur Seite.",
        "aboutP3": "Jeden Tag präsentieren wir ein neues vergessenes Wort, damit Sie Ihren Wortschatz erweitern und die Welt mit den Augen vergangener Generationen betrachten können.",
        "feat1Title": "Moderne Entsprechungen",
        "feat1Desc": "Jedes archaische Wort enthält ein direktes zeitgenössisches Synonym",
        "feat2Title": "Zwei reiche Sprachen",
        "feat2Desc": "Über 2.000 russische und englische Worte mit strenger Trennung",
        "feat3Title": "Archaismen & Historismen",
        "feat3Desc": "Klare Unterscheidung zwischen ersetzten Worten und untergegangenen Realien",
        "feat4Title": "Interaktive Quiz",
        "feat4Desc": "Stellen Sie Ihr Wissen bei „Bedeutung erraten“ oder beim Synonym-Abgleich auf die Probe",
        "footerCopy": "© 2026 Forgotten Words. Die Bewahrung der Sprache der Vergangenheit für die Zukunft.",
        "footerMade": "Mit ❤️ für Wortliebhaber gemacht",
        "etymology": "Etymologie",
        "usageLabel": "Verwendung",
        "synonymLabel": "Moderne Entsprechung:",
        "navWordOfDay": "Wort des Tages",
        "navDictionary": "Wörterbuch",
        "navQuiz": "Quiz",
        "navSuggest": "Wort vorschlagen",
        "navAbout": "Über das Projekt",
        "tabRu": "Russische Worte",
        "tabEn": "Englische Worte",
        "quizTitle": "Literarisches Wortquiz",
        "quizSubtitle": "Stellen Sie Ihren historischen Wortschatz und Ihre Intuition auf die Probe!",
        "score": "Punktzahl",
        "streak": "Serie",
        "nextQuestion": "Nächstes Wort",
        "quizModeMeaning": "📖 Bedeutung erraten",
        "quizModeSynonym": "✨ Modernes Synonym",
        "quizPromptMeaning": "Wählen Sie die korrekte Bedeutung dieses Wortes:",
        "quizPromptSynonym": "Wählen Sie die korrekte moderne Entsprechung:",
        "quizFeedbackCorrect": "Richtig! Hervorragende Gelehrsamkeit!",
        "quizFeedbackWrong": "Nicht ganz. Die richtige Antwort lautet:",
        "suggestTitle": "Ein vergessenes Wort vorschlagen",
        "suggestSubtitle": "Ein seltenes Wort gehört oder in einem alten Buch entdeckt? Reichen Sie Ihren Vorschlag ein – unsere Redakteure werden ihn prüfen!",
        "suggestWordLabel": "Wort *",
        "suggestWordPlaceholder": "Z. B. Übermorgen",
        "suggestLangLabel": "Sprache",
        "suggestSynonymLabel": "Moderne Entsprechung / Synonym *",
        "suggestSynonymPlaceholder": "Z. B. Der Tag nach morgen",
        "suggestTypeLabel": "Wortart",
        "suggestCategoryLabel": "Kategorie",
        "suggestMeaningLabel": "Detaillierte Bedeutung & Definition *",
        "suggestMeaningPlaceholder": "Was dieses Wort einst bedeutete und wie es in alten Zeiten verwendet wurde...",
        "suggestSourceLabel": "Wo haben Sie dieses Wort entdeckt? (Buch, Folklore, Überlieferung)",
        "suggestSourcePlaceholder": "Z. B. Shakespeare, Hamlet oder lokaler Mundartausdruck",
        "suggestAuthorLabel": "Ihr Name oder Pseudonym (für die Nennung auf der Karte)",
        "suggestAuthorPlaceholder": "Z. B. Arthur der Bibliophile",
        "submitWord": "Zur Prüfung einreichen",
        "themeTitle": "Thema",
        "toastCopiedWord": "Wort in die Zwischenablage kopiert!",
        "toastWordAdded": "Wortvorschlag zur Prüfung eingereicht! Vielen Dank!",
        "heroSearchTitle": "Das Wörterbuch der verlorenen Worte durchsuchen",
        "heroSearchSubtitle": "Über 2.000 seltene und archaische Worte mit direkten modernen Entsprechungen",
        "heroSearchPlaceholder": "Nach archaischem Wort oder modernem Synonym suchen (z. B. Weiland, DDrall)...",
        "liveSearchSeeAll": "Alle passenden Worte im Wörterbuch anzeigen",
        "liveSearchNone": "Keine vergessenen Worte zu dieser Suchanfrage gefunden",
        "actionLangLabel": "Sprache:",
        "actionFontLabel": "Schriftart:",
        "actionThemeLabel": "Thema:",
        "themePapyrus": "Papyrus",
        "themeDark": "Dunkel",
        "navDonate": "Unterstützen",
        "footerDonate": "☕ Den Autor unterstützen",
        "donateTitle": "Den Autor & das Projekt unterstützen",
        "donateDesc": "Forgotten Words ist ein unabhängiges Non-Profit-Projekt, das sich der Bewahrung seltener und archaischer Worte widmet. Ihre Spende hilft dabei, Server zu finanzieren, den Wortschatz zu erweitern und neue Funktionen zu entwickeln!",
        "boostySub": "Abo oder einmalige Spende per Karte",
        "cloudtipsSub": "Schnelle Überweisung per Karte & Zahlungs-Apps",
        "donattySub": "Bequemes Trinkgeld mit wenigen Klicks",
        "donateNote": "Wir danken allen, die die Geschichte und Schönheit der Sprache schätzen! ❤️",
        "statLangsLabel": "Sprachen"
    },
    "it": {
        "logoTitle": "Forgotten Words",
        "logoSubtitle": "Dizionario delle Parole Perdute",
        "wordOfDay": "Parola del Giorno",
        "randomWord": "Parola Casuale",
        "copy": "Copia",
        "copied": "Copiato!",
        "wordsInDict": "parole nel dizionario",
        "eras": "epoche storiche",
        "languages": "lingue",
        "dictionary": "Dizionario",
        "dictDesc": "Esplora le parole che un tempo echeggiavano in ogni focolare",
        "language": "Lingua:",
        "era": "Epoca:",
        "category": "Categoria:",
        "wordType": "Tipo di parola:",
        "all": "Tutte",
        "allWords": "Tutte le parole",
        "allCategories": "Tutte le categorie",
        "allEras": "Tutte le epoche",
        "typeArchaism": "🏛️ Arcaismi (con sinonimo moderno)",
        "typeHistoricism": "📜 Storicismi (reliquie storiche)",
        "searchPlaceholder": "Cerca una parola o un sinonimo moderno...",
        "notFound": "Nessuna parola trovata. Prova una ricerca diversa o reimposta i filtri.",
        "showMore": "Mostra Altro",
        "aboutTitle": "Informazioni sul Progetto",
        "aboutP1": "<strong>Forgotten Words</strong> è un dizionario interattivo di parole arcaiche e obsolete delle lingue russa e inglese.",
        "aboutP2": "Raccogliamo arcaismi, storicismi e parole rare dalla letteratura classica — da Puškin e Dostoevskij a Shakespeare e Dickens — abbinando ciascuna ai rispettivi equivalenti moderni.",
        "aboutP3": "Ogni giorno presentiamo una nuova parola dimenticata, affinché tu possa arricchire il tuo vocabolario e osservare il mondo attraverso gli occhi delle generazioni passate.",
        "feat1Title": "Controparti Moderne",
        "feat1Desc": "Ogni parola arcaica include un sinonimo contemporaneo diretto",
        "feat2Title": "Due Ricche Lingue",
        "feat2Desc": "Oltre 2.000 parole russe e inglesi rigorosamente separate",
        "feat3Title": "Arcaismi e Storicismi",
        "feat3Desc": "Netta distinzione tra parole sostituite e realtà scomparse",
        "feat4Title": "Quiz Interattivi",
        "feat4Desc": "Metti alla prova la tua erudizione in \"Indovina il significato\" o nell'abbinamento dei sinonimi",
        "footerCopy": "© 2026 Forgotten Words. Custodire la lingua del passato per il futuro.",
        "footerMade": "Realizzato con ❤️ per gli amanti delle parole",
        "etymology": "Etimologia",
        "usageLabel": "Uso",
        "synonymLabel": "Equivalente moderno:",
        "navWordOfDay": "Parola del Giorno",
        "navDictionary": "Dizionario",
        "navQuiz": "Quiz",
        "navSuggest": "Suggerisci Parola",
        "navAbout": "Informazioni",
        "tabRu": "Parole russe",
        "tabEn": "Parole inglesi",
        "quizTitle": "Quiz di Letteratura",
        "quizSubtitle": "Metti alla prova il tuo vocabolario storico e il tuo intuito!",
        "score": "Punteggio",
        "streak": "Serie",
        "nextQuestion": "Parola Successiva",
        "quizModeMeaning": "📖 Indovina il Significato",
        "quizModeSynonym": "✨ Sinonimo Moderno",
        "quizPromptMeaning": "Scegli il significato corretto di questa parola:",
        "quizPromptSynonym": "Seleziona l'equivalente moderno corretto:",
        "quizFeedbackCorrect": "Corretto! Straordinaria erudizione!",
        "quizFeedbackWrong": "Non proprio. La risposta corretta era:",
        "suggestTitle": "Suggerisci una Parola Dimenticata",
        "suggestSubtitle": "Hai sentito una parola rara o l'hai incontrata in un vecchio libro? Invia la tua proposta: i nostri curatori la esamineranno!",
        "suggestWordLabel": "Parola *",
        "suggestWordPlaceholder": "Ad es., Dopodomani",
        "suggestLangLabel": "Lingua",
        "suggestSynonymLabel": "Equivalente / sinonimo moderno *",
        "suggestSynonymPlaceholder": "Ad es., Il giorno dopo domani",
        "suggestTypeLabel": "Tipo di parola",
        "suggestCategoryLabel": "Categoria",
        "suggestMeaningLabel": "Significato dettagliato e definizione *",
        "suggestMeaningPlaceholder": "Cosa significava questa parola e come veniva usata nei tempi antichi...",
        "suggestSourceLabel": "Dove hai scoperto questa parola? (libro, folklore, anziani)",
        "suggestSourcePlaceholder": "Ad es., Shakespeare, Amleto o un detto popolare",
        "suggestAuthorLabel": "Il tuo nome o pseudonimo (per il riconoscimento)",
        "suggestAuthorPlaceholder": "Ad es., Arturo il Bibliofilo",
        "submitWord": "Invia per la Revisione",
        "themeTitle": "Tema",
        "toastCopiedWord": "Parola copiata negli appunti!",
        "toastWordAdded": "Suggerimento inviato per la revisione! Grazie!",
        "heroSearchTitle": "Cerca nel Dizionario delle Parole Perdute",
        "heroSearchSubtitle": "Oltre 2.000 parole rare e arcaiche con i loro equivalenti moderni diretti",
        "heroSearchPlaceholder": "Cerca per parola arcaica o sinonimo moderno (es. Forse, Anco)...",
        "liveSearchSeeAll": "Visualizza tutte le parole corrispondenti nel dizionario",
        "liveSearchNone": "Nessuna parola dimenticata corrisponde alla ricerca",
        "actionLangLabel": "Lingua:",
        "actionFontLabel": "Carattere:",
        "actionThemeLabel": "Tema:",
        "themePapyrus": "Papiro",
        "themeDark": "Scuro",
        "navDonate": "Sostieni",
        "footerDonate": "☕ Sostieni l'Autore",
        "donateTitle": "Sostieni l'Autore e il Progetto",
        "donateDesc": "Forgotten Words è un progetto indipendente senza scopo di lucro dedicato alla salvaguardia di parole rare e arcaiche. La tua donazione aiuta a coprire i costi dei server, espandere il lessico e sviluppare nuove funzioni!",
        "boostySub": "Abbonamento o donazione singola tramite carta",
        "cloudtipsSub": "Trasferimento rapido con carta e app di pagamento",
        "donattySub": "Una comoda mancia in pochi clic",
        "donateNote": "Grazie di cuore a tutti coloro che custodiscono la storia e la bellezza della lingua! ❤️",
        "statLangsLabel": "lingue"
    },
    "fr": {
        "logoTitle": "Mots Oubliés",
        "logoSubtitle": "Dictionnaire des mots perdus",
        "wordOfDay": "Mot du jour",
        "randomWord": "Mot aléatoire",
        "copy": "Copier",
        "copied": "Copié !",
        "wordsInDict": "mots dans le dictionnaire",
        "eras": "époques historiques",
        "languages": "langues",
        "dictionary": "Dictionnaire",
        "dictDesc": "Explorez les mots qui résonnaient autrefois dans chaque foyer",
        "language": "Langue :",
        "era": "Époque :",
        "category": "Catégorie :",
        "wordType": "Type de mot :",
        "all": "Tous",
        "allWords": "Tous les mots",
        "allCategories": "Toutes les catégories",
        "allEras": "Toutes les époques",
        "typeArchaism": "🏛️ Archaïsmes (possèdent un synonyme moderne)",
        "typeHistoricism": "📜 Historicismes (témoins d'une réalité disparue)",
        "searchPlaceholder": "Rechercher un mot ou un synonyme moderne...",
        "notFound": "Aucun mot trouvé. Essayez une autre recherche ou réinitialisez les filtres.",
        "showMore": "Afficher plus",
        "aboutTitle": "À propos du projet",
        "aboutP1": "<strong>Mots Oubliés</strong> est un dictionnaire interactif de termes archaïques et désuets issus des langues russe et anglaise.",
        "aboutP2": "Nous rassemblons archaïsmes, historicismes et mots rares tirés de la littérature classique — de Pouchkine et Dostoïevski à Shakespeare et Dickens — en associant chacun à son équivalent moderne.",
        "aboutP3": "Chaque jour, nous mettons à l'honneur un nouveau mot oublié pour vous permettre d'enrichir votre vocabulaire et de contempler le monde à travers le regard des générations passées.",
        "feat1Title": "Équivalents modernes",
        "feat1Desc": "Chaque mot archaïque s'accompagne d'un synonyme contemporain direct",
        "feat2Title": "Deux langues riches",
        "feat2Desc": "Plus de 2 000 mots russes et anglais rigoureusement classés",
        "feat3Title": "Archaïsmes et historicismes",
        "feat3Desc": "Une distinction claire entre mots remplacés et réalités éteintes",
        "feat4Title": "Quiz interactifs",
        "feat4Desc": "Testez vos connaissances grâce au « Devinage de sens » ou à l'accord de synonymes",
        "footerCopy": "© 2026 Mots Oubliés. Préserver la langue d'hier pour l'avenir.",
        "footerMade": "Créé avec ❤️ pour les amoureux des mots",
        "etymology": "Étymologie",
        "usageLabel": "Usage",
        "synonymLabel": "Équivalent moderne :",
        "navWordOfDay": "Mot du jour",
        "navDictionary": "Dictionnaire",
        "navQuiz": "Quiz",
        "navSuggest": "Suggérer un mot",
        "navAbout": "À propos",
        "tabRu": "Mots russes",
        "tabEn": "Mots anglais",
        "quizTitle": "Quiz du vocabulaire littéraire",
        "quizSubtitle": "Testez votre érudition historique et votre intuition !",
        "score": "Score",
        "streak": "Série",
        "nextQuestion": "Mot suivant",
        "quizModeMeaning": "📖 Deviner le sens",
        "quizModeSynonym": "✨ Synonyme moderne",
        "quizPromptMeaning": "Choisissez la définition exacte de ce mot :",
        "quizPromptSynonym": "Sélectionnez l'équivalent moderne adéquat :",
        "quizFeedbackCorrect": "Exact ! Quelle splendide érudition !",
        "quizFeedbackWrong": "Presque. La bonne réponse était :",
        "suggestTitle": "Suggérer un mot oublié",
        "suggestSubtitle": "Vous avez surpris un mot rare ou l'avez croisé dans un vieux livre ? Soumettez votre proposition — nos éditeurs l'examineront !",
        "suggestWordLabel": "Mot *",
        "suggestWordPlaceholder": "Ex. : Surlendemain",
        "suggestLangLabel": "Langue",
        "suggestSynonymLabel": "Équivalent moderne / synonyme *",
        "suggestSynonymPlaceholder": "Ex. : Le jour d'après demain",
        "suggestTypeLabel": "Type de mot",
        "suggestCategoryLabel": "Catégorie",
        "suggestMeaningLabel": "Sens détaillé et définition *",
        "suggestMeaningPlaceholder": "Ce que signifiait ce mot et comment il était employé autrefois...",
        "suggestSourceLabel": "Où avez-vous découvert ce mot ? (livre, folklore, aïeul)",
        "suggestSourcePlaceholder": "Ex. : Shakespeare, Hamlet, ou dicton populaire",
        "suggestAuthorLabel": "Votre nom ou pseudonyme (pour le crédit de la carte)",
        "suggestAuthorPlaceholder": "Ex. : Arthur le Bibliophile",
        "submitWord": "Soumettre pour examen",
        "themeTitle": "Thème",
        "toastCopiedWord": "Mot copié dans le presse-papier !",
        "toastWordAdded": "Suggestion de mot transmise pour examen ! Merci !",
        "heroSearchTitle": "Parcourir le Dictionnaire des mots perdus",
        "heroSearchSubtitle": "Plus de 2 000 mots rares et archaïques dotés de leurs équivalents modernes",
        "heroSearchPlaceholder": "Rechercher par mot archaïque ou synonyme (ex. jadis, naguère)...",
        "liveSearchSeeAll": "Voir tous les mots correspondants dans le dictionnaire",
        "liveSearchNone": "Aucun mot oublié ne correspond à votre recherche",
        "actionLangLabel": "Langue :",
        "actionFontLabel": "Police :",
        "actionThemeLabel": "Thème :",
        "themePapyrus": "Papyrus",
        "themeDark": "Sombre",
        "navDonate": "Soutenir",
        "footerDonate": "☕ Soutenir l'auteur",
        "donateTitle": "Soutenir l'auteur et le projet",
        "donateDesc": "Mots Oubliés est un projet indépendant et sans but lucratif voué à la préservation des mots rares et archaïques. Votre contribution aide à financer les serveurs, enrichir le lexique et développer de nouvelles fonctionnalités !",
        "boostySub": "Abonnement ou don ponctuel par carte",
        "cloudtipsSub": "Transfert rapide par carte et applications de paiement",
        "donattySub": "Pourboire aisé en quelques clics",
        "donateNote": "Merci à tous ceux qui chérissent l'histoire et la beauté de la langue ! ❤️",
        "statLangsLabel": "langues"
    }
};
